In [2]:
import os

import wfdb
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import ast

In [52]:
dataset_loc = "../ptb-xl"

In [53]:
# !ls {dataset_loc}

In [54]:
path = os.path.join(dataset_loc, "ptbxl_database.csv")
df = pd.read_csv(path, index_col='ecg_id')
df

,patient_id,age,sex,height,weight,nurse,site,device,recording_date,report,...,validated_by_human,baseline_drift,static_noise,burst_noise,electrodes_problems,extra_beats,pacemaker,strat_fold,filename_lr,filename_hr
ecg_id,,,,,,,,,,,,,,,,,,,,,
1,15709.0,56.0,1,NaN,63.0,2.0,0.0,CS-12 E,1984-11-09 09:17:34,sinusrhythmus periphere niederspannung,...,True,NaN,", I-V1,",NaN,NaN,NaN,NaN,3,records100/00000/00001_lr,records500/00000/00001_hr
2,13243.0,19.0,0,NaN,70.0,2.0,0.0,CS-12 E,1984-11-14 12:55:37,sinusbradykardie sonst normales ekg,...,True,NaN,NaN,NaN,NaN,NaN,NaN,2,records100/00000/00002_lr,records500/00000/00002_hr
3,20372.0,37.0,1,NaN,69.0,2.0,0.0,CS-12 E,1984-11-15 12:49:10,sinusrhythmus normales ekg,...,True,NaN,NaN,NaN,NaN,NaN,NaN,5,records100/00000/00003_lr,records500/00000/00003_hr
4,17014.0,24.0,0,NaN,82.0,2.0,0.0,CS-12 E,1984-11-15 13:44:57,sinusrhythmus normales ekg,...,True,", II,III,AVF",NaN,NaN,NaN,NaN,NaN,3,records100/00000/00004_lr,records500/00000/00004_hr
5,17448.0,19.0,1,NaN,70.0,2.0,0.0,CS-12 E,1984-11-17 10:43:15,sinusrhythmus normales ekg,...,True,", III,AVR,AVF",NaN,NaN,NaN,NaN,NaN,4,records100/00000/00005_lr,records500/00000/00005_hr
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21833,17180.0,67.0,1,NaN,NaN,1.0,2.0,AT-60 3,2001-05-31 09:14:35,ventrikul√Ñre extrasystole(n) sinustachykardie ...,...,True,NaN,", alles,",NaN,NaN,1ES,NaN,7,records100/21000/21833_lr,records500/21000/21833_hr
21834,20703.0,300.0,0,NaN,NaN,1.0,2.0,AT-60 3,2001-06-05 11:33:39,sinusrhythmus lagetyp normal qrs(t) abnorm ...,...,True,NaN,NaN,NaN,NaN,NaN,NaN,4,records100/21000/21834_lr,records500/21000/21834_hr
21835,19311.0,59.0,1,NaN,NaN,1.0,2.0,AT-60 3,2001-06-08 10:30:27,sinusrhythmus lagetyp normal t abnorm in anter...,...,True,NaN,", I-AVR,",NaN,NaN,NaN,NaN,2,records100/21000/21835_lr,records500/21000/21835_hr
21836,8873.0,64.0,1,NaN,NaN,1.0,2.0,AT-60 3,2001-06-09 18:21:49,supraventrikul√Ñre extrasystole(n) sinusrhythmu...,...,True,NaN,NaN,NaN,NaN,SVES,NaN,8,records100/21000/21836_lr,records500/21000/21836_hr
21837,11744.0,68.0,0,NaN,NaN,1.0,2.0,AT-60 3,2001-06-11 16:43:01,sinusrhythmus p-sinistrocardiale lagetyp norma...,...,True,NaN,", I-AVL,",NaN,NaN,NaN,NaN,9,records100/21000/21837_lr,records500/21000/21837_hr

In [55]:
df.scp_codes = df.scp_codes.apply(lambda x: ast.literal_eval(x))
df.scp_codes

ecg_id
1                 {'NORM': 100.0, 'LVOLT': 0.0, 'SR': 0.0}
2                             {'NORM': 80.0, 'SBRAD': 0.0}
3                               {'NORM': 100.0, 'SR': 0.0}
4                               {'NORM': 100.0, 'SR': 0.0}
5                               {'NORM': 100.0, 'SR': 0.0}
                               ...
21833    {'NDT': 100.0, 'PVC': 100.0, 'VCLVH': 0.0, 'ST...
21834             {'NORM': 100.0, 'ABQRS': 0.0, 'SR': 0.0}
21835                           {'ISCAS': 50.0, 'SR': 0.0}
21836                           {'NORM': 100.0, 'SR': 0.0}
21837                           {'NORM': 100.0, 'SR': 0.0}
Name: scp_codes, Length: 21799, dtype: object

In [56]:
agg_df = pd.read_csv(os.path.join(dataset_loc, 'scp_statements.csv'), index_col=0)
agg_df = agg_df[agg_df.diagnostic == 1]
agg_df

,description,diagnostic,form,rhythm,diagnostic_class,diagnostic_subclass,Statement Category,SCP-ECG Statement Description,AHA code,aECG REFID,CDISC Code,DICOM Code
NDT,non-diagnostic T abnormalities,1.0,1.0,NaN,STTC,STTC,other ST-T descriptive statements,non-diagnostic T abnormalities,NaN,NaN,NaN,NaN
NST_,non-specific ST changes,1.0,1.0,NaN,STTC,NST_,Basic roots for coding ST-T changes and abnorm...,non-specific ST changes,145.0,MDC_ECG_RHY_STHILOST,NaN,NaN
DIG,digitalis-effect,1.0,1.0,NaN,STTC,STTC,other ST-T descriptive statements,suggests digitalis-effect,205.0,NaN,NaN,NaN
LNGQT,long QT-interval,1.0,1.0,NaN,STTC,STTC,other ST-T descriptive statements,long QT-interval,148.0,NaN,NaN,NaN
NORM,normal ECG,1.0,NaN,NaN,NORM,NORM,Normal/abnormal,normal ECG,1.0,NaN,NaN,F-000B7
IMI,inferior myocardial infarction,1.0,NaN,NaN,MI,IMI,Myocardial Infarction,inferior myocardial infarction,161.0,NaN,NaN,NaN
ASMI,anteroseptal myocardial infarction,1.0,NaN,NaN,MI,AMI,Myocardial Infarction,anteroseptal myocardial infarction,165.0,NaN,NaN,NaN
LVH,left ventricular hypertrophy,1.0,NaN,NaN,HYP,LVH,Ventricular Hypertrophy,left ventricular hypertrophy,142.0,NaN,C71076,NaN
LAFB,left anterior fascicular block,1.0,NaN,NaN,CD,LAFB/LPFB,Intraventricular and intra-atrial Conduction d...,left anterior fascicular block,101.0,MDC_ECG_BEAT_BLK_ANT_L_HEMI,C62267,D3-33140
ISC_,non-specific ischemic,1.0,NaN,NaN,STTC,ISC_,Basic roots for coding ST-T changes and abnorm...,ischemic ST-T changes,226.0,NaN,NaN,NaN
IRBBB,incomplete right bundle branch block,1.0,NaN,NaN,CD,IRBBB,Intraventricular and intra-atrial Conduction d...,incomplete right bundle branch block,105.0,MDC_ECG_BEAT_RBB_BLK_INCOMP,C71048,D3-33112
1AVB,first degree AV block,1.0,NaN,NaN,CD,_AVB,"Sinus node dysfunction, atrial and AV-conducti...",first degree AV block,NaN,MDC_ECG_RHY_AV_HEART_BLK_DEG_1,C111088,NaN
IVCD,non-specific intraventricular conduction distu...,1.0,NaN,NaN,CD,IVCD,Intraventricular and intra-atrial Conduction d...,non-specific intraventricular conduction distu...,107.0,MDC_ECG_BEAT_BLK_IVCD,C62271,D3-33000
ISCAL,ischemic in anterolateral leads,1.0,NaN,NaN,STTC,ISCA,ischemic ST-T changes,in anterolateral leads,NaN,NaN,NaN,NaN
CRBBB,complete right bundle branch block,1.0,NaN,NaN,CD,CRBBB,Intraventricular and intra-atrial Conduction d...,(complete) right bundle branch block,106.0,MDC_ECG_BEAT_RBB_BLK_COMP,C62270,D3-33110
CLBBB,complete left bundle branch block,1.0,NaN,NaN,CD,CLBBB,Intraventricular and intra-atrial Conduction d...,(complete) left bundle branch block,104.0,MDC_ECG_BEAT_LBB_BLK_COMP,C62269,D3-33120 or 122752
ILMI,inferolateral myocardial infarction,1.0,NaN,NaN,MI,IMI,Myocardial Infarction,inferolateral myocardial infarction,NaN,NaN,NaN,NaN
LAO/LAE,left atrial overload/enlargement,1.0,NaN,NaN,HYP,LAO/LAE,Atrial statements,left atrial overload/enlargement,140.0,NaN,NaN,NaN
AMI,anterior myocardial infarction,1.0,NaN,NaN,MI,AMI,Myocardial Infarction,anterior myocardial infarction,160.0,NaN,NaN,NaN
ALMI,anterolateral myocardial infarction,1.0,NaN,NaN,MI,AMI,Myocardial Infarction,anterolateral myocardial infarction,NaN,NaN,NaN,NaN
ISCIN,ischemic in inferior leads,1.0,NaN,NaN,STTC,ISCI,ischemic ST-T changes,in inferior leads,NaN,NaN,NaN,NaN
INJAS,subendocardial injury in anteroseptal leads,1.0,NaN,NaN,MI,AMI,ischemic ST-T changes compatible with subendoc...,in anteroseptal leads,NaN,NaN,NaN,NaN
LMI,lateral myocardial infarction,1.0,NaN,NaN,MI,LMI,Myocardial Infarction,lateral myocardial infarction,163.0,NaN,NaN,NaN
ISCIL,ischemic in inferolateral leads,1.0,NaN,NaN,STTC,ISCI,ischemic ST-T changes,in inferolateral leads,NaN,NaN,NaN,NaN
LPFB,left posterior fascicular block,1.0,NaN,NaN,CD,LAFB/LPFB,Intraventricular and intra-atrial Conduction d...,left posterior fascicular block,102.0,MDC_ECG_BEAT_BLK_POS_L_HEMI,C62268,D3-33150
ISCAS,ischemic in anteroseptal leads,1.0,NaN,NaN,STTC,ISCA,ischemic ST-T changes,in anteroseptal leads,NaN,NaN,NaN,NaN
INJAL,subendocardial injury in anterolateral leads,1.0,NaN,NaN,MI,AMI,ischemic ST-T changes compatible with subendoc...,in anterolateral leads,NaN,NaN,NaN,NaN
ISCLA,ischemic in lateral leads,1.0,NaN,NaN,STTC,ISCA,ischemic ST-T changes,in lateral leads,NaN,NaN,NaN,NaN
RVH,right ventricular hypertrophy,1.0,NaN,NaN,HYP,RVH,Ventricular Hypertrophy,right ventricular hypertrophy,143.0,NaN,C71077,NaN
ANEUR,ST-T changes compatible with ventricular aneurysm,1.0,NaN,NaN,STTC,STTC,other ST-T descriptive statements,ST-T changes compatible with ventricular aneurysm,227.0,NaN,NaN,NaN
RAO/RAE,right atrial overload/enlargement,1.0,NaN,NaN,HYP,RAO/RAE,Atrial statements,right atrial overload/enlargement,141.0,NaN,NaN,NaN
EL,electrolytic disturbance or drug (former EDIS),1.0,NaN,NaN,STTC,STTC,physiopathological nature of ST-T changes,compatible with electrolyte abnormalities,NaN,NaN,NaN,NaN
WPW,Wolf-Parkinson-White syndrome,1.0,NaN,NaN,CD,WPW,Intraventricular and intra-atrial Conduction d...,Wolff-Parkinson-White syndrome,NaN,MDC_ECG_RHY_WPW_UNK,C35132,NaN
ILBBB,incomplete left bundle branch block,1.0,NaN,NaN,CD,ILBBB,Intraventricular and intra-atrial Conduction d...,incomplete left bundle branch block,NaN,MDC_ECG_BEAT_LBB_BLK_INCOMP,C71047,NaN
IPLMI,inferoposterolateral myocardial infarction,1.0,NaN,NaN,MI,IMI,Myocardial Infarction,inferoposterolateral myocardial infarction,NaN,NaN,NaN,NaN
ISCAN,ischemic in anterior leads,1.0,NaN,NaN,STTC,ISCA,ischemic ST-T changes,in anterior leads,NaN,NaN,NaN,NaN
IPMI,inferoposterior myocardial infarction,1.0,NaN,NaN,MI,IMI,Myocardial Infarction,inferoposterior myocardial infarction,NaN,NaN,NaN,NaN
SEHYP,septal hypertrophy,1.0,NaN,NaN,HYP,SEHYP,Ventricular Hypertrophy,septal hypertrophy,NaN,NaN,NaN,NaN
INJIN,subendocardial injury in inferior leads,1.0,NaN,NaN,MI,IMI,ischemic ST-T changes compatible with subendoc...,in inferior leads,NaN,NaN,NaN,NaN
INJLA,subendocardial injury in lateral leads,1.0,NaN,NaN,MI,AMI,ischemic ST-T changes compatible with subendoc...,in lateral leads,NaN,NaN,NaN,NaN
PMI,posterior myocardial infarction,1.0,NaN,NaN,MI,PMI,Myocardial Infarction,posterior myocardial infarction,162.0,NaN,NaN,NaN
3AVB,third degree AV block,1.0,NaN,NaN,CD,_AVB,"Sinus node dysfunction, atrial and AV-conducti...",third degree AV block,88.0,MDC_ECG_RHY_AV_HEART_BLK_DEG_3,C111091,D3-32102
INJIL,subendocardial injury in inferolateral leads,1.0,NaN,NaN,MI,IMI,ischemic ST-T changes compatible with subendoc...,in inferolateral leads,NaN,NaN,NaN,NaN
2AVB,second degree AV block,1.0,NaN,NaN,CD,_AVB,"Sinus node dysfunction, atrial and AV-conducti...",second degree AV block,NaN,MDC_ECG_RHY_AV_HEART_BLK_DEG_2,C62016,R-F81AE

In [57]:
def aggregate_diagnostic(y_dic):
    tmp = []
    for key in y_dic.keys():
        if key in agg_df.index:
            tmp.append(agg_df.loc[key].diagnostic_class)
    return list(set(tmp))

# Apply diagnostic superclass
df['diagnostic_superclass'] = df.scp_codes.apply(aggregate_diagnostic)

In [58]:
df['diagnostic_superclass'].value_counts()

diagnostic_superclass
[NORM]                 9069
[MI]                   2532
[STTC]                 2400
[CD]                   1708
[CD, MI]               1297
[STTC, HYP]             781
[MI, STTC]              599
[HYP]                   535
[CD, STTC]              471
[]                      411
[CD, NORM]              407
[STTC, MI, HYP]         340
[CD, HYP]               300
[CD, MI, STTC]          220
[MI, HYP]               183
[STTC, CD, HYP]         156
[CD, MI, HYP]           111
[STTC, MI, CD, HYP]      93
[CD, MI, STTC, HYP]      61
[CD, STTC, HYP]          55
[STTC, NORM]             28
[MI, STTC, HYP]          21
[CD, HYP, MI]             6
[CD, STTC, NORM]          5
[CD, STTC, MI]            3
[CD, HYP, NORM]           2
[HYP, NORM]               2
[STTC, CD, HYP, MI]       1
[CD, MI, HYP, NORM]       1
[HYP, CD, STTC, MI]       1
Name: count, dtype: int64

In [59]:
df = df[df['diagnostic_superclass'].apply(lambda x: x != [])]
df

,patient_id,age,sex,height,weight,nurse,site,device,recording_date,report,...,baseline_drift,static_noise,burst_noise,electrodes_problems,extra_beats,pacemaker,strat_fold,filename_lr,filename_hr,diagnostic_superclass
ecg_id,,,,,,,,,,,,,,,,,,,,,
1,15709.0,56.0,1,NaN,63.0,2.0,0.0,CS-12 E,1984-11-09 09:17:34,sinusrhythmus periphere niederspannung,...,NaN,", I-V1,",NaN,NaN,NaN,NaN,3,records100/00000/00001_lr,records500/00000/00001_hr,[NORM]
2,13243.0,19.0,0,NaN,70.0,2.0,0.0,CS-12 E,1984-11-14 12:55:37,sinusbradykardie sonst normales ekg,...,NaN,NaN,NaN,NaN,NaN,NaN,2,records100/00000/00002_lr,records500/00000/00002_hr,[NORM]
3,20372.0,37.0,1,NaN,69.0,2.0,0.0,CS-12 E,1984-11-15 12:49:10,sinusrhythmus normales ekg,...,NaN,NaN,NaN,NaN,NaN,NaN,5,records100/00000/00003_lr,records500/00000/00003_hr,[NORM]
4,17014.0,24.0,0,NaN,82.0,2.0,0.0,CS-12 E,1984-11-15 13:44:57,sinusrhythmus normales ekg,...,", II,III,AVF",NaN,NaN,NaN,NaN,NaN,3,records100/00000/00004_lr,records500/00000/00004_hr,[NORM]
5,17448.0,19.0,1,NaN,70.0,2.0,0.0,CS-12 E,1984-11-17 10:43:15,sinusrhythmus normales ekg,...,", III,AVR,AVF",NaN,NaN,NaN,NaN,NaN,4,records100/00000/00005_lr,records500/00000/00005_hr,[NORM]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21833,17180.0,67.0,1,NaN,NaN,1.0,2.0,AT-60 3,2001-05-31 09:14:35,ventrikul√Ñre extrasystole(n) sinustachykardie ...,...,NaN,", alles,",NaN,NaN,1ES,NaN,7,records100/21000/21833_lr,records500/21000/21833_hr,[STTC]
21834,20703.0,300.0,0,NaN,NaN,1.0,2.0,AT-60 3,2001-06-05 11:33:39,sinusrhythmus lagetyp normal qrs(t) abnorm ...,...,NaN,NaN,NaN,NaN,NaN,NaN,4,records100/21000/21834_lr,records500/21000/21834_hr,[NORM]
21835,19311.0,59.0,1,NaN,NaN,1.0,2.0,AT-60 3,2001-06-08 10:30:27,sinusrhythmus lagetyp normal t abnorm in anter...,...,NaN,", I-AVR,",NaN,NaN,NaN,NaN,2,records100/21000/21835_lr,records500/21000/21835_hr,[STTC]
21836,8873.0,64.0,1,NaN,NaN,1.0,2.0,AT-60 3,2001-06-09 18:21:49,supraventrikul√Ñre extrasystole(n) sinusrhythmu...,...,NaN,NaN,NaN,NaN,SVES,NaN,8,records100/21000/21836_lr,records500/21000/21836_hr,[NORM]
21837,11744.0,68.0,0,NaN,NaN,1.0,2.0,AT-60 3,2001-06-11 16:43:01,sinusrhythmus p-sinistrocardiale lagetyp norma...,...,NaN,", I-AVL,",NaN,NaN,NaN,NaN,9,records100/21000/21837_lr,records500/21000/21837_hr,[NORM]

In [60]:
Z = pd.DataFrame(0, index=df.index, columns=['NORM', 'MI', 'STTC', 'CD', 'HYP'], dtype='int')
Z

        NORM  MI  STTC  CD  HYP
ecg_id
1          0   0     0   0    0
2          0   0     0   0    0
3          0   0     0   0    0
4          0   0     0   0    0
5          0   0     0   0    0
...      ...  ..   ...  ..  ...
21833      0   0     0   0    0
21834      0   0     0   0    0
21835      0   0     0   0    0
21836      0   0     0   0    0
21837      0   0     0   0    0

[21388 rows x 5 columns]

In [61]:
for i in Z.index:
    for k in df.loc[i].diagnostic_superclass:
        Z.loc[i, k] = 1

In [62]:
Z

        NORM  MI  STTC  CD  HYP
ecg_id
1          1   0     0   0    0
2          1   0     0   0    0
3          1   0     0   0    0
4          1   0     0   0    0
5          1   0     0   0    0
...      ...  ..   ...  ..  ...
21833      0   0     1   0    0
21834      1   0     0   0    0
21835      0   0     1   0    0
21836      1   0     0   0    0
21837      1   0     0   0    0

[21388 rows x 5 columns]

In [66]:
Z.describe()

               NORM            MI          STTC            CD           HYP
count  21388.000000  21388.000000  21388.000000  21388.000000  21388.000000
mean       0.444829      0.255704      0.244763      0.229007      0.123854
std        0.496958      0.436266      0.429957      0.420204      0.329423
min        0.000000      0.000000      0.000000      0.000000      0.000000
25%        0.000000      0.000000      0.000000      0.000000      0.000000
50%        0.000000      0.000000      0.000000      0.000000      0.000000
75%        1.000000      1.000000      0.000000      0.000000      0.000000
max        1.000000      1.000000      1.000000      1.000000      1.000000

In [67]:
df.columns

Index(['patient_id', 'age', 'sex', 'height', 'weight', 'nurse', 'site',
       'device', 'recording_date', 'report', 'scp_codes', 'heart_axis',
       'infarction_stadium1', 'infarction_stadium2', 'validated_by',
       'second_opinion', 'initial_autogenerated_report', 'validated_by_human',
       'baseline_drift', 'static_noise', 'burst_noise', 'electrodes_problems',
       'extra_beats', 'pacemaker', 'strat_fold', 'filename_lr', 'filename_hr',
       'diagnostic_superclass'],
      dtype='object')

In [74]:
to_keep = ['patient_id', 'age', 'sex', 'strat_fold', 'filename_lr', 'filename_hr']
ECG_df = df[to_keep]

In [75]:
ECG_df

,patient_id,age,sex,strat_fold,filename_lr,filename_hr
ecg_id,,,,,,
1,15709.0,56.0,1,3,records100/00000/00001_lr,records500/00000/00001_hr
2,13243.0,19.0,0,2,records100/00000/00002_lr,records500/00000/00002_hr
3,20372.0,37.0,1,5,records100/00000/00003_lr,records500/00000/00003_hr
4,17014.0,24.0,0,3,records100/00000/00004_lr,records500/00000/00004_hr
5,17448.0,19.0,1,4,records100/00000/00005_lr,records500/00000/00005_hr
...,...,...,...,...,...,...
21833,17180.0,67.0,1,7,records100/21000/21833_lr,records500/21000/21833_hr
21834,20703.0,300.0,0,4,records100/21000/21834_lr,records500/21000/21834_hr
21835,19311.0,59.0,1,2,records100/21000/21835_lr,records500/21000/21835_hr
21836,8873.0,64.0,1,8,records100/21000/21836_lr,records500/21000/21836_hr
21837,11744.0,68.0,0,9,records100/21000/21837_lr,records500/21000/21837_hr

In [76]:
Z

        NORM  MI  STTC  CD  HYP
ecg_id
1          1   0     0   0    0
2          1   0     0   0    0
3          1   0     0   0    0
4          1   0     0   0    0
5          1   0     0   0    0
...      ...  ..   ...  ..  ...
21833      0   0     1   0    0
21834      1   0     0   0    0
21835      0   0     1   0    0
21836      1   0     0   0    0
21837      1   0     0   0    0

[21388 rows x 5 columns]

In [78]:
labeled_df = ECG_df.merge(Z, left_index=True, right_index=True)

In [79]:
labeled_df.to_csv(os.path.join(dataset_loc, "labeled_df.csv"))

In [80]:
df = pd.read_csv(os.path.join(dataset_loc, "labeled_df.csv"))

In [81]:
df

,ecg_id,patient_id,age,sex,strat_fold,filename_lr,filename_hr,NORM,MI,STTC,CD,HYP
0,1,15709.0,56.0,1,3,records100/00000/00001_lr,records500/00000/00001_hr,1,0,0,0,0
1,2,13243.0,19.0,0,2,records100/00000/00002_lr,records500/00000/00002_hr,1,0,0,0,0
2,3,20372.0,37.0,1,5,records100/00000/00003_lr,records500/00000/00003_hr,1,0,0,0,0
3,4,17014.0,24.0,0,3,records100/00000/00004_lr,records500/00000/00004_hr,1,0,0,0,0
4,5,17448.0,19.0,1,4,records100/00000/00005_lr,records500/00000/00005_hr,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
21383,21833,17180.0,67.0,1,7,records100/21000/21833_lr,records500/21000/21833_hr,0,0,1,0,0
21384,21834,20703.0,300.0,0,4,records100/21000/21834_lr,records500/21000/21834_hr,1,0,0,0,0
21385,21835,19311.0,59.0,1,2,records100/21000/21835_lr,records500/21000/21835_hr,0,0,1,0,0
21386,21836,8873.0,64.0,1,8,records100/21000/21836_lr,records500/21000/21836_hr,1,0,0,0,0
21387,21837,11744.0,68.0,0,9,records100/21000/21837_lr,records500/21000/21837_hr,1,0,0,0,0

In [88]:
df['NORM'].value_counts()

NORM
0    11874
1     9514
Name: count, dtype: int64

In [83]:
df['MI'].value_counts()

MI
0    15919
1     5469
Name: count, dtype: int64

In [84]:
df['STTC'].value_counts()

STTC
0    16153
1     5235
Name: count, dtype: int64

In [85]:
df['CD'].value_counts()

CD
0    16490
1     4898
Name: count, dtype: int64

In [86]:
df['HYP'].value_counts()

HYP
0    18739
1     2649
Name: count, dtype: int64